### ISSUE TITLE
decryption algorithm for new rabbistream encryption?

### ISSUE THREAD

**Issue by ks3rr** [v3nka/keys#1]
Hello, 
the keys seem to have changed for rabbit stream, and they are in new format. Consequently, decryption algorithm seems to have changed. Can you update the decryption algorithm for it.

"rabbitstream": {
"keys": {
"v": "48474",
"h": "201540f9e24505a7f8ffd4d612c7a4a9b257a70d",
"b": 1878522368,
"agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0",
"key": "LDOGaTMwig=="
},
"updated_at": 1709284782
},

how we will decrypt sources using this?

**Comment by v3nka** [comment]
its ip locked so keys are useless unless requests are made through same ip, kindly ignore these keys for now
